export default {
  login: "norstein21",
  id: 50061406,
  node_id: "MDQ6VXNlcjUwMDYxNDA2",
  avatar_url: "https://avatars.githubusercontent.com/u/50061406?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/norstein21",
  html_url: "https://github.com/norstein21",
  followers_url: "https://api.github.com/users/norstein21/followers",
  following_url: "https://api.github.com/users/norstein21/following{/other_user}",
  gists_url: "https://api.github.com/users/norstein21/gists{/gist_id}",
  starred_url: "https://api.github.com/users/norstein21/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/norstein21/subscriptions",
  organizations_url: "https://api.github.com/users/norstein21/orgs",
  repos_url: "https://api.github.com/users/norstein21/repos",
  events_url: "https://api.github.com/users/norstein21/events{/privacy}",
  received_events_url: "https://api.github.com/users/norstein21/received_events",
  type: "User",
  site_admin: false,
  name: "Habie Purwokusumo Putrapandowo",
  company: null,
  blog: "",
  location: "Indonesia",
  email: null,
  hireable: true,
  bio: "Hello, good people!",
  twitter_username: null,
  public_repos: 29,
  public_gists: 0,
  followers: 0,
  following: 1,
  created_at: "2019-04-28T00:14:27Z",
  updated_at: "2022-11-17T10:41:33Z"
}
